Rookio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from viewer import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.welcome, name='welcome'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('add_room/', views.add_room, name='add_room'),
    path('rooms_overview/', views.rooms_overview, name='rooms_overview'),

    path('my_items/', views.my_items_view, name='my_items'),
    path('check_nickname/', views.check_nickname_view, name='check_nickname'),

    path('my_rooms/', views.my_rooms, name='my_rooms'),
    path('my_rooms/<int:room_id>/edit_room', views.edit_room, name='edit_room'),
    path('room_detail/<int:room_id>/', views.room_detail, name='room_detail'),

    path('room_detail/<int:room_id>/toggle_visibility/', views.toggle_room_visibility, name='toggle_room_visibility'),

    path('room_detail/<int:room_id>/show_items', views.show_items, name='show_items'),
    path('room_detail/<int:room_id>/add_item', views.add_item, name='add_item'),
    path('room_detail/<int:room_id>/edit_item', views.edit_item, name='edit_item'),

    path('room_detail/<int:room_id>/items/<int:item_id>/edit/', views.edit_menu_item, name='edit_menu_item'),
    path('room_detail/<int:room_id>/items/<int:item_id>/delete/', views.delete_menu_item, name='delete_menu_item'),

    # detail of the room from "Rooms Overview"
    path('room_detail_with_items/<int:room_id>/', views.room_detail_with_items, name='room_detail_with_items'),
]

# my note - enable Django to serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.core.validators import MinValueValidator, MaxValueValidator

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Tag(TimeStamp):
    name = models.CharField(max_length=25, unique=True)

    def __str__(self) -> str:
        return f'Model Tag - name: {self.name}'


class PersonOwner(TimeStamp):

    PERMISSION_CHOICES = (
        ('PERMISSION1ADMIN', 'Admin/Creator'),  # DO NOT CHANGE the content or order - views.py def add_room(request)
        ('PERMISSION2MOD', 'Moderator'),
        ('PERMISSION3VIEWER', 'Viewer'),
    )

    user_person_owner: User = models.OneToOneField(User, on_delete=models.CASCADE, related_name='owner_profile')
    date_of_birth = models.DateField(null=True, blank=True)
    permission = models.CharField(max_length=30, choices=PERMISSION_CHOICES, default='permission3viewer')

    def __str__(self) -> str:
        return f'Model PersonOwner - {self.user_person_owner.first_name} {self.user_person_owner.last_name}'


class Template(TimeStamp):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self) -> str:
        return f'Model Template - name: {self.name}'


class Room(TimeStamp):

    ROOM_TYPE_CHOICES = (
        ('event', 'Event'),
        ('service', 'Service'),
    )

    name = models.CharField(max_length=80)
    owners = models.ManyToManyField(PersonOwner, related_name="rooms")
    room_type = models.CharField(max_length=20, choices=ROOM_TYPE_CHOICES)
    tags = models.ManyToManyField(Tag, related_name="rooms")
    description = models.TextField(max_length=1000)  # default form widget for this field is a Textarea -
    # https://docs.djangoproject.com/en/4.2/ref/forms/widgets/#django.forms.Textarea
    place = models.CharField(max_length=150)
    gps_description = models.CharField(max_length=150, blank=True)
    gps_lat = models.DecimalField(max_digits=9, decimal_places=6,
                                  null=True,
                                  blank=True,
                                  validators=[MinValueValidator(-90), MaxValueValidator(90)])
    gps_lng = models.DecimalField(max_digits=9, decimal_places=6,
                                  null=True,
                                  blank=True,
                                  validators=[MinValueValidator(-180), MaxValueValidator(180)])
    date = models.DateField()
    time = models.TimeField()
    outdoor = models.BooleanField(blank=True, default=False)
    contact_public = models.CharField(max_length=100)
    contact_after_assignment = models.CharField(max_length=100, null=True, blank=True)
    age_restriction = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(120)],
                                                       null=True, blank=True)
    age_recommendation = models.CharField(max_length=80, null=True, blank=True)
    minimum_participants = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)], null=True, blank=True)
    maximum_participants = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)], null=True, blank=True)
    paid_to_be_unique = models.BooleanField(default=False)
    hidden_from_public = models.BooleanField(default=True)
    template = models.ForeignKey(Template, on_delete=models.CASCADE, related_name="rooms", null=True, blank=True)

    def __str__(self) -> str:
        return f'Model Room - name: {self.name}'


class MenuItem(TimeStamp):
    item_name = models.CharField(max_length=50, unique=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0)])
    duration = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)], null=True, blank=True)
    number_of_pieces = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="menu_items")

    def __str__(self) -> str:
        return f'Model MenuItem - item name: {self.item_name}'


class PersonParticipant(TimeStamp):
    user_person_participant: User = models.OneToOneField(
                                                        User,
                                                        on_delete=models.CASCADE,
                                                        null=True, blank=True,
                                                        related_name='participant_profile')
    nickname_unregistered_participant = models.CharField(max_length=255, unique=True, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    menu_items = models.ManyToManyField(MenuItem, through='PersonParticipantMenuItem', related_name="participants")

    def __str__(self) -> str:
        return f'Model PersonParticipant - ' \
               f'{self.user_person_participant.first_name} {self.user_person_participant.last_name}'

    def clean(self):
        if not self.user_person_participant and not self.nickname_unregistered_participant:
            raise ValidationError('Either username or nickname of the participant must be set.')

    def save(self, *args, **kwargs):
        if not self.user_person_participant and not self.nickname_unregistered_participant:
            raise ValidationError('Either username or nickname of the participant must be set.')
        super().save(*args, **kwargs)


class PersonParticipantMenuItem(models.Model):
    participant = models.ForeignKey(PersonParticipant, on_delete=models.CASCADE)
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    count = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)], null=True)

    class Meta:
        unique_together = ('participant', 'menu_item')

    def __str__(self) -> str:
        return f' Model PersonParticipantMenuItem - {self.participant} - {self.menu_item}: {self.count}'


LIMIT_MB = 20
BYTES_PER_LIMIT = 1024 ** 2
SUBTYPE_OF_IMAGE = ['jpeg', 'gif', 'png']


def validate_image(image):
    file_size = image.file.size
    if file_size > LIMIT_MB * BYTES_PER_LIMIT:
        raise ValidationError(f"Max size of file is {LIMIT_MB} MB")
    # check the file MIME type, e.g. image/png
    main, sub = image.content_type.split('/')
    if not (main == 'image' and sub in SUBTYPE_OF_IMAGE):
        raise ValidationError(f'Please use one of these image types: {", ".join(SUBTYPE_OF_IMAGE)}.')


class Image(TimeStamp):
    image_file = models.ImageField(upload_to='images/', validators=[validate_image])
    image_height = models.IntegerField()
    image_width = models.IntegerField()
    description = models.CharField(max_length=50)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="images")
    thumbnail = ImageSpecField(source='image_file',  # source referring to the column 'image_file'
                               processors=[ResizeToFill(100, 100)],
                               format='JPEG',
                               options={'quality': 60})

    def __str__(self) -> str:
        return f'Model Image - description: {self.description}'

viewer/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.core.exceptions import ValidationError

from viewer.models import Room, Tag, MenuItem


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    email = forms.EmailField(max_length=64, required=True, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class RoomForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(format='%Y-%m-%d'),
                           input_formats=('%Y-%m-%d',))
    time = forms.TimeField(widget=forms.TimeInput(format='%H:%M:%S'),
                           input_formats=('%H:%M',))

    class Meta:
        model = Room
        fields = ['name',
                  'room_type',
                  'description',
                  'place',
                  'gps_description',
                  'gps_lat',
                  'gps_lng',
                  'date',
                  'time',
                  'outdoor',
                  'contact_public',
                  'contact_after_assignment',
                  'age_restriction',
                  'age_recommendation',
                  'minimum_participants',
                  'maximum_participants'
                  ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:  # if this is a saved instance
            self.initial['date'] = self.instance.date.strftime('%Y-%m-%d')
            self.initial['time'] = self.instance.time.strftime('%H:%M')


class TagForm(forms.Form):
    name = forms.CharField(max_length=25, label='Tags')

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if not name:
            raise ValidationError("Tag name cannot be empty.")
        # this part is no longer needed because we WANT an existing tag to be assigned to a newly created room
        # if Tag.objects.filter(name=name).exists():
        #     raise ValidationError("Tag with this name already exists.")
        return name


class MenuItemForm(forms.ModelForm):
    class Meta:
        model = MenuItem
        fields = ['item_name', 'price', 'duration', 'number_of_pieces']

        widgets = {
            'item_name':
                forms.TextInput(attrs={'class': 'bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full '
                                                'py-2 px-4 text-gray-700 leading-tight focus:outline-none '
                                                'focus:bg-white focus:border-blue-500'
                                       }
                                ),
            'price':
                forms.NumberInput(attrs={'class': 'bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full '
                                                  'py-2 px-4 text-gray-700 leading-tight focus:outline-none '
                                                  'focus:bg-white focus:border-blue-500'
                                         }
                                  ),
            'duration':
                forms.NumberInput(attrs={'class': 'bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full '
                                                  'py-2 px-4 text-gray-700 leading-tight focus:outline-none '
                                                  'focus:bg-white focus:border-blue-500'
                                         }
                                  ),
            'number_of_pieces':
                forms.NumberInput(attrs={'class': 'bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full '
                                                  'py-2 px-4 text-gray-700 leading-tight focus:outline-none '
                                                  'focus:bg-white focus:border-blue-500'
                                         }
                                  ),
        }

viewer/templates/add_item.html
{% extends 'room_detail.html' %}
{% load filters %}

{% block modify %}
<div class="py-20 container mx-auto px-4">
    <h2 class="text-2xl font-bold mb-4">Add Menu Item:</h2>
    <form method="post" class="bg-white p-6 rounded shadow-lg">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        {% for field in form %}
            <div class="mb-4">
                <label for="{{ field.id_for_label }}" class="block mb-2">{{ field.label }}</label>
                <input id="{{ field.id_for_label }}" class="border p-2 w-full {% if field.errors %}border-red-500{% else %}border-gray-200{% endif %}" type="text" name="{{ field.name }}" value="{{ field.value|default:'' }}">
                {% if field.errors %}
                    <div class="text-red-500">{{ field.errors }}</div>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="mt-4 bg-blue-500 text-white p-2 rounded">Add Item</button>
    </form>

    {% if room.menu_items.exists %}
        <h2 class="text-2xl font-bold mb-4 mt-6">Current Items:</h2>
        <div class="grid md:grid-cols-3 gap-4">
            {% for item in room.menu_items.all %}
            <div class="border rounded p-2 border-red-900 inline-flex flex-col items-start">
                <h3 class="text-xl font-bold">{{ item.item_name }}</h3>
                <p class="mt-2"><span class="font-bold">Price:</span> {{ item.price }} €</p>
                {% if item.duration %}
                <p class="mt-2"><span class="font-bold">Duration:</span>
                {% if item.duration == 1 %}
                    {{ item.duration }} minute
                {% elif item.duration < 61 %}
                   {{ item.duration }} minutes
                {% elif item.duration < 120 %}
                    {{ item.duration|minutes_to_hours }} hour
                {% else %}
                    {{ item.duration|minutes_to_hours }} hours
                {% endif %}
                </p>
                {% endif %}
                <p class="mt-2"><span class="font-bold">Number of Pieces:</span> {{ item.number_of_pieces }}</p>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="text-red-500 mt-6">No item has been added for this room yet.</p>
    {% endif %}

</div>
{% endblock %}

viewer/templates/delete_menu_item.html
{% extends 'room_detail.html' %}

{% block modify %}
<div class="container mx-auto px-4">
    <h2 class="text-2xl font-bold mb-4">Delete Item:</h2>
    <p>Are you sure you want to delete "{{ item.item_name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="bg-red-500 text-white p-2 rounded">I'm sure, DELETE item</button>
    </form>
</div>
{% endblock %}

viewer/templates/edit_menu_item.html
{% extends 'room_detail.html' %}

{% block modify %}
<div class="container mx-auto px-4">
    <h2 class="text-2xl font-bold mb-4">Edit Item:</h2>
    <form method="post" class="bg-white p-6 rounded shadow-lg">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        {% for field in form %}
            <div class="mb-4">
                <label for="{{ field.id_for_label }}" class="block mb-2">{{ field.label }}</label>
                <input id="{{ field.id_for_label }}" class="border p-2 w-full {% if field.errors %}border-red-500{% else %}border-gray-200{% endif %}" type="text" name="{{ field.name }}" value="{{ field.value|default:'' }}">
                {% if field.errors %}
                    <div class="text-red-500">{{ field.errors }}</div>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="bg-blue-500 text-white p-2 rounded">Save Item</button>
    </form>
</div>
{% endblock %}

viewer/templates/my_rooms.html
{% extends 'base.html' %}
{% load tz %}

{% block title %}Rookio - My Rooms{% endblock title %}

{% block content %}
<div class="container mx-auto px-4">
    <h2 class="text-2xl font-bold mb-4">My Rooms:</h2>
    <ul>
        {% for room in rooms %}
        <li class="mb-4 border rounded p-4 border-red-900">
            <a href="{% url 'room_detail' room.id %}" class="block hover:bg-gray-200">
                <h3 class="text-xl font-bold">{{ room.name }}</h3>
{#                TODO decide what to add here#}

                {% for tag in room.tags.all %}
                    {{ tag.name }}{% if not forloop.last %} ‧ {% endif %}
                {% empty %}
                    No tags.
                {% endfor %}

                <p class="mt-2"><span class="font-bold">Type:</span> {{ room.get_room_type_display }}</p>
                <p class="mt-2"><span class="font-bold">Description:</span> {{ room.description }}</p>
                <p class="mt-2"><span class="font-bold">Place:</span> {{ room.place }}</p>
            </a>
        </li>
        {% empty %}
        <li class="text-red-500 animate-blink">{{request.user.username}}, you have not yet created any room.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

viewer/templates/room_overview_detail.html
{% extends 'base.html' %}
{% load filters %}


{% block title %}Room Detail{% endblock title %}

{% block content %}
<div class="container mx-auto px-4">
    <h2 class="text-2xl font-bold">{{ room.name }}</h2>
    <p><span class="font-bold">Type:</span> {{ room.get_room_type_display }}</p>
    <p><span class="font-bold">Date:</span> {{ room.date|date:'d.m.Y' }}</p>
    <p><span class="font-bold">Description:</span> {{ room.description }}</p>

    <h3 class="text-xl font-bold mt-4">Items</h3>

    <form id="menu-form" method="POST">
        {% csrf_token %}

        {% if not user.is_authenticated %}
        <div class="my-4">
            <label for="nickname" class="block text-sm font-medium text-gray-700">Enter Nickname:</label>
            <input type="text" id="nickname" name="nickname" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" required>
        </div>
        {% endif %}

        <div class="grid grid-cols-4 gap-4">
            {% for item in menu_items %}
            <div id="item-{{ item.id }}" class="item relative rounded-lg border-2 border-black p-4 shadow-lg">
                <h4 class="text-lg font-bold">{{ item.item_name }}</h4>
                <p><span class="font-bold">Price:</span> {{ item.price }} €</p>
                <p><span class="font-bold">Duration time:</span>
                {% if item.duration == 1 %}
                        {{ item.duration }} minute
                    {% elif item.duration < 61 %}
                       {{ item.duration }} minutes
                    {% else %}
                        {{ item.duration|minutes_to_hours }}
                    {% endif %}
                </p>
                <p><span class="font-bold">Count:</span> {{ item.number_of_pieces }}</p>

                <div class="flex justify-between items-center mt-4">
                    <span class="font-bold">Quantity:</span>
                    <div>
                        <button type="button" class="quantity-decrease bg-red-500 text-white rounded-lg px-2 py-1 mr-1">-</button>
                        <input type="number" min="0" max="{{ item.number_of_pieces|add:"-1" }}" value="0" class="quantity-input border-2 border-gray-300 rounded-lg w-12 text-center" name="quantity-{{ item.id }}">
                        <button type="button" class="quantity-increase bg-green-500 text-white rounded-lg px-2 py-1 ml-1">+</button>
                    </div>
                </div>

            </div>
            {% empty %}
            <p>No items available.</p>
            {% endfor %}
        </div>

        {% if room.menu_items.exists %}
        <div class="text-center mt-4">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Confirm selected items
            </button>
        </div>
        {% endif %}
        {% if messages %}
        <div class="mt-4 mx-auto">
            {% for message in messages %}
            <div class="{% if message.tags == 'error' %}animate-pulse text-red-500 border-l-4 border-red-500{% else %}font-bold{% endif %} px-4 py-3 mb-3" role="alert">
                <p class="font-bold">Notification</p>
                <p>{{ message }}</p>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </form>
</div>

<script>
window.onload = function() {
    // Get all the quantity inputs
    const quantityInputs = document.querySelectorAll('.quantity-input');

    quantityInputs.forEach(input => {
        // Get the associated increase and decrease buttons
        const decreaseButton = input.parentElement.querySelector('.quantity-decrease');
        const increaseButton = input.parentElement.querySelector('.quantity-increase');

        // Decrease quantity by 1 when the "-" button is clicked
        decreaseButton.addEventListener('click', function() {
            if (input.value > 0) {
                input.value = parseInt(input.value) - 1;
            }
        });

        // Increase quantity by 1 when the "+" button is clicked
        increaseButton.addEventListener('click', function() {
            let currentValue = parseInt(input.value.trim(), 10);
            let maxValue = parseInt(input.max.trim(), 10);
            console.log(`Current value: ${currentValue}, Max value: ${maxValue}`);
            if (currentValue < maxValue) {
                input.value = currentValue + 1;
            } else {
                console.warn(`Reached max value for input`);
            }
            console.log(`Updated value: ${input.value}`)
        });
    });
};
</script>

{% endblock %}

viewer/templates/rooms_overview.html
{% extends 'base.html' %}
{% load tz %}

{% block title %}Rookio - Rooms Overview{% endblock title %}

{% block content %}

<div class="flex justify-center mt-4 mb-8">
    <form method="get" action="{% url 'rooms_overview' %}" class="flex">
        <input type="text" name="tag_search" value="{{ query }}" placeholder="Enter tag to search..." class="border rounded-l px-4 py-2">
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-r hover:bg-blue-600">Use filter</button>
    </form>
</div>

<div class="container mx-auto px-4 grid grid-cols-3 gap-4">
    {% for room in rooms %}
    <div class="room relative rounded-b-lg border-black p-4 shadow-md shadow-black hover:shadow-blue-700">

{#        Overlay#}
        <div class="overlay fixed inset-0 bg-black bg-opacity-50 hidden z-10"></div>

{#        Default room information#}
        <div class="default-info">
            <h3 class="text-xl font-bold">{{ room.name }}</h3>
            <p class="mt-2">
                {% for tag in room.tags.all %}
                    {{ tag.name }}{% if not forloop.last %}, {% endif %}
                {% empty %}
                    No tags.
                {% endfor %}
            </p>
            <p class="mt-2"><span class="font-bold">Type:</span> {{ room.get_room_type_display }}</p>
            <p class="mt-2"><span class="font-bold">Date:</span> {{ room.date|date:'d.m.Y' }}</p>
        {#     TODO - fix timezone#}
            <p class="mt-2"><span class="font-bold">Time:</span> {{ room.time|time:'H:i' }}</p>
        </div>

        <div class="additional-info-container fixed inset-0 flex items-center justify-center hidden z-20">

{#            Extended room information#}
            <div class="additional-info relative max-h-screen w-3/5 overflow-auto rounded-xl bg-white p-4">

{#                Join button#}
                <a href="{% url 'room_detail_with_items' room.id %}" class="join-button absolute right-0 top-1 mr-4 mt-4 animate-bounce rounded-b-full border-b-4 border-r-2 border-black bg-fuchsia-950 px-10 text-2xl text-white shadow-md shadow-black hover:shadow-fuchsia-950">Join</a>

                <h3 class="text-xl font-bold">{{ room.name }}</h3>
                <p class="mt-2">
                    {% for tag in room.tags.all %}
                        {{ tag.name }}{% if not forloop.last %}, {% endif %}
                    {% empty %}
                        No tags.
                    {% endfor %}
                </p>
                <p class="mt-2"><span class="font-bold">Type:</span> {{ room.get_room_type_display }}</p>
                <p class="mt-2"><span class="font-bold">Date:</span> {{ room.date|date:'d.m.Y' }}</p>
            {#     TODO - fix timezone#}
                <p class="mt-2"><span class="font-bold">Time:</span> {{ room.time|time:'H:i' }}</p>

                <p class="mt-2"><span class="font-bold">Description:</span> {{ room.description }}</p>

                <div class="flex mb-4">
                    <div class="flex-1 pr-4">
                        <p class="mt-2"><span class="font-bold">Place:</span> {{ room.place }}</p>
                        <p class="mt-2"><span class="font-bold">GPS place description:</span> {{ room.gps_description }}</p>
                        <p class="mt-2"><span class="font-bold">GPS latitude of place:</span> {{ room.gps_lat }}</p>
                        <p class="mt-2"><span class="font-bold">GPS longitude of place:</span> {{ room.gps_lng }}</p>
                        <p class="mt-2"><span class="font-bold">Contact:</span> {{ room.contact_public }}</p>
            {#            TODO - Additional Contact -> make it visible only for event attendants#}
                        <p class="mt-2"><span class="font-bold">Additional Contact:</span> {{ room.contact_after_assignment }}</p>
                        <p class="mt-2"><span class="font-bold">Age restriction:</span> {{ room.age_restriction }}</p>
                        <p class="mt-2"><span class="font-bold">Age recommendation:</span> {{ room.age_recommendation }}</p>
                        <p class="mt-2"><span class="font-bold">Number of available places:</span> {{ number_of_available_places }}</p>
            {#            TODO - make it visible only if Room type is event#}
                        <p class="mt-2"><span class="font-bold">Minimum number of people to start the event:</span> {{ room.minimum_participants }}</p>
                    </div>

                    <div class="flex-1">
                        <div id="overviewGoogleMap_{{ room.id }}" class="h-96 w-full border rounded"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <p class="text-red-500">No rooms available.</p>
    {% endfor %}
</div>

<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}&libraries=places"></script>

<script>
    // Get all room elements
    const rooms = document.querySelectorAll('.room');

    rooms.forEach(room => {
        const overlay = room.querySelector('.overlay');
        const additionalInfoContainer = room.querySelector('.additional-info-container');
        const additionalInfo = room.querySelector('.additional-info');

        // Handle room click
        room.addEventListener('click', event => {
            // Hide all other additional info containers and overlays
            rooms.forEach(r => {
                if (r !== room) {
                    r.querySelector('.additional-info-container').classList.add('hidden');
                    r.querySelector('.overlay').classList.add('hidden');
                }
            });

            // Toggle this room's additional info container and overlay
            additionalInfoContainer.classList.toggle('hidden');
            overlay.classList.toggle('hidden');
        });

        // Handle overlay click
        overlay.addEventListener('click', () => {
            additionalInfoContainer.classList.add('hidden');
            overlay.classList.add('hidden');
        });

        // Stop propagation of click events on additional info
        additionalInfo.addEventListener('click', event => {
            event.stopPropagation();
        });
    });


    const roomsData = {{ serialized_rooms|safe }};

    function initOverviewMap(room, index) {
        const roomLocation = {
            lat: parseFloat(room.fields.gps_lat),
            lng: parseFloat(room.fields.gps_lng)
        };

        const map = new google.maps.Map(document.getElementById('overviewGoogleMap_' + room.pk), {
            center: roomLocation,
            zoom: 15
        });

        new google.maps.Marker({
            position: roomLocation,
            map: map,
            title: room.fields.gps_description
        });
    }

    document.addEventListener("DOMContentLoaded", function() {
        roomsData.forEach(initOverviewMap);
    })

</script>

{% endblock %}